version: "3"

services:
  postgres:
    image: "postgres:12.10-alpine"
    restart: "always"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: "redis:latest"

  nginx:
    restart: "always"
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - medin
      - wetalk

  medin:
    build:
      context: ./medin
    volumes:
      - /app/node_modules
      - ./medin:/app
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=postgres
      - PGPORT=5432
      - REDIS_URL=redis
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
      - redis

  wetalk:
    build:
      context: ./we-talk
    volumes:
      - /app/node_modules
      - ./we-talk:/app
    depends_on:
      - medin
