source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

gem "active_model_serializers", "~> 0.10.13"
gem "bootsnap", require: false
gem "devise", "~> 4.8", ">= 4.8.1"
gem "devise_masquerade", "~> 1.3", ">= 1.3.10"
gem "jsbundling-rails"
gem "name_of_person", "~> 1.1", ">= 1.1.1"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "rails", "~> 7.0.2", ">= 7.0.2.3"
gem "redis", "~> 4.0"
gem "responders", github: "heartcombo/responders", branch: "main"
gem "sidekiq", "~> 6.4", ">= 6.4.1"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails", "~> 6.2"
end

group :development do
  gem "letter_opener_web", "~> 2.0"
  gem "solargraph-standardrb"
  gem "standard"
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "shoulda", "~> 4.0"
  gem "webdrivers"
end
